apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: alertmaker
  name: alertmaker-clusterrole
rules:
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
    - watch
    - list
    - get
  - apiGroups:
    - ""
    resources:
      - namespaces
      - pods
      - services
      - replicationcontrollers
      - persistentvolumeclaims
      - persistentvolumes
    verbs:
      - watch
      - list
      - get
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - list
      - watch
      - create
      - get
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - list
      - watch
      - create
      - get            
  # - apiGroups:
  #   - batch
  #   resources:
  #     - jobs
  #     - cronjobs
  #   verbs:
  #     - watch
  #     - list
  #     - get
  # - apiGroups:
  #   - batch
  #   - extensions
  #   resources:
  #   - jobs
  #   verbs:
  #   - get
  #   - list
  #   - patch
  #   - watch
  #   - create
