apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
spec:
  replicas: 1
  selector:
    matchLabels:
      role: kubectl
  template:
    metadata:
      labels:
        role: kubectl
    spec:
      serviceAccountName: kubectl-sa
      automountServiceAccountToken: true
      containers:
      - image: dmsqlczzz/grafana_alert_maker_k8s:main
        name: kubelet
        tty: true
        securityContext:
          privileged: true
        volumeMounts:
        - name: kube-config
          mountPath: /root/.kube/
      volumes:
      - name: kube-config
        hostPath:
          path: /root/.kube/
          # path: /home/$USER/.kube/