apiVersion: v1
kind: Secret
metadata:
  labels:
    app: kubectl
  name: grafana-alert-maker
  namespace: monitor
type: Opaque
data:
  admin-password: cXdlcjEyMzQ=
  admin-user: YWRtaW4=
  grafana-url: Z3JhZmFuYS5tb25pdG9yLnN2Ywo=